version: "3"
services:
  mydb:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo_database
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

