version: "3"
services:
  app:
    container_name: demo_go_api
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - mydb
    networks:
      - demo_network
    volumes:
      - ./logs:/root/logs
  mydb:
    image: postgres
    container_name: postgres_container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo_database
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - demo_network
volumes:
  db-data:
  logs:

networks:
  demo_network:
